### ISSUE TITLE
Scraper todo list

### ISSUE THREAD

**Issue by ondenman** [everypolitician-scrapers/spain-congreso#2]
I've opened this issue so we can keep track on what needs doing.

- [ ] Scraper set up
- [ ] Scrape members list
- [ ] Scrape individual member pages
- [ ] Scrape historical memberships for individual members
- [ ] Merge historical memberships

**Comment by ondenman** [comment]
I'm going to add this to the multipart issue in ep-data: https://github.com/everypolitician/everypolitician-data/issues/27746
